# Generated by Django 4.0.2 on 2022-02-21 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('views_cnt', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('exposure', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('impressions_cnt', models.IntegerField(default=1)),
                ('text_length', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('image_cnt', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('residence_time', models.FloatField(blank=True, default=0, null=True)),
                ('like_cnt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_like_cnt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_views_cnt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_residence_time', models.FloatField(blank=True, default=0, null=True)),
                ('importance', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testdata', to=settings.AUTH_USER_MODEL, verbose_name='테스트 데이터')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testproject.testdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testproject.testdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
