# Generated by Django 3.2 on 2022-02-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_alter_testdata_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='residence_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
