# Generated by Django 3.2 on 2022-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='image_cnt',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='impressions_cnt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='text_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='views_cnt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
