# Generated by Django 3.2 on 2022-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0005_auto_20220216_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
