# Generated by Django 3.2 on 2022-02-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0007_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='exposure',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
