# Generated by Django 3.2 on 2022-02-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0008_testdata_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='impressions_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
