# Generated by Django 3.2 on 2022-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0010_auto_20220218_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='user_like_cnt',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
