# Generated by Django 3.2 on 2022-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0011_testdata_user_like_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='user_residence_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='user_views_cnt',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
